<?php
// module/Client/view/client/client/edit.phtml:

$title = 'Modifier un client';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$nom = $form->get('nom');
$nom->setAttribute('class', 'form-control');
$nom->setAttribute('placeholder', 'Nom du client');

$prenom = $form->get('prenom');
$prenom->setAttribute('class', 'form-control');
$prenom->setAttribute('placeholder', 'Prénom');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('client', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($nom) ?>
    <?= $this->formElement($nom) ?>
    <?= $this->formElementErrors()->render($nom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($prenom) ?>
    <?= $this->formElement($prenom) ?>
    <?= $this->formElementErrors()->render($prenom, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag(); 