<?php
$title = 'Mes Articles';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('article', ['action' => 'add']) ?>">Ajouter un Article</a>
</p>

<table class="table">
    <tr>
        <th>Désignation</th>
        <th>Prix Unitaire</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($paginator as $article) : ?>
        <tr>
            <td><?= $this->escapeHtml($article->designation) ?></td>
            <td><?= $this->escapeHtml($article->prix) ?></td>
            <td>
                <a href="<?= $this->url('article', ['action' => 'edit', 'id' => $article->id]) ?>">Modifier</a>
                <a href="<?= $this->url('article', ['action' => 'delete', 'id' => $article->id]) ?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?= $this->paginationControl(
    $this->paginator,
    'sliding',
    'partial/paginator',
    [
        'route' => 'article'
    ]
)
?>
